### ISSUE TITLE
error decoding results

### ISSUE THREAD

**Issue by githubxnoob** [philpw99/Stash_Helper#14]
i opened a video on stash browser but when i click play current scene or alt+p i get

error decoding results.
 
error getting result:

the potplayer path is current. same with vlc

**Comment by philpw99** [comment]
What browser do you use ? And the URL of the video, is it like "http://127.0.0.1/scenes/123" or something else ?

**Comment by philpw99** [comment]
Stash 17 has a fundamental change: The "path" in each scene no longer exist. Instead it uses a "files" collection, which means it will no be compatible with all previous implements, I guess lots of plug-ins which handle files will break.

Personally I like this implement, because from now on each scene can have multiple files with different resolutions or codecs.
The fix is also relatively easy. I think I will even give you a choice of which file to play, if there are more than one file for that scene.

**Comment by philpw99** [comment]
OK, 2.4.1 is out, which is compatible with Stash v17 and above.
https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.1

**Comment by githubxnoob** [comment]
i tried the new version. this time either i get **no error** when pressing alt+p/ right click and select that  "play current scene" button.

or i get the same error i got[ before.](https://github.com/philpw99/Stash_Helper/issues/14#issue-1448424314)

i tried it on both chrome and brave browser. i tried uninstalling stash helper and doing a fresh install of this new update.( although it somehow knows the configuration)


anyways its not working for me. i am sorry.
stash v0.17.2

**Comment by philpw99** [comment]
Thank you for trying it out. I got no problem to use alt-p or "play current scene" button with PotPlayer.
I tested with both Edge and Chrome. The video files play just fine.
So I am wondering if you are using "Remote" or "Local" mode. What's the URL you use, is it "localhost" or "127.0.0.1" or something?

**Comment by githubxnoob** [comment]
I'm using remote mode. The url is something like 192.168.x.xxx

**Comment by philpw99** [comment]
I just tested remote mode with Chrome. No problems either. Also the changes in Stash v17 wouldn't affect the remote mode of Stash Helper, only the local mode was affected and needed to change. 
Maybe you can try just copy the steam link from a scene in Stash, then open this URL in PotPlayer, and see what happens? Because basically Stash helper is doing things like this with PotPlayer:
` PotPlayerMini64.exe "http://192.168.x.xxx:9999/scene/1234/stream" `

**Comment by githubxnoob** [comment]
> I just tested remote mode with Chrome. No problems either. Also the changes in Stash v17 wouldn't affect the remote mode of Stash Helper, only the local mode was affected and needed to change. Maybe you can try just copy the steam link from a scene in Stash, then open this URL in PotPlayer, and see what happens? Because basically Stash helper is doing things like this with PotPlayer: `PotPlayerMini64.exe "http://192.168.x.xxx:9999/scene/1234/stream"`

turns out it didnt play because http://192.168.x.xxx:9999/scene/1234/stream is not enough. since i have password enabled in stashapp webapp. the url needed apikey. otherwise it wouldnt work.

http://192.168.x.xxx:9999/scene/4817/stream?apikey=

this above url works in all players.

the api key can be found here http://192.168.x.xx:9999/settings?tab=security

**Comment by philpw99** [comment]
I see. Thank you so much for telling me about it! I will fix this in the next version.

**Comment by philpw99** [comment]
New version is out. It has much better support for password protected Stash:
https://github.com/philpw99/Stash_Helper/releases/tag/v2.4.2

**Comment by githubxnoob** [comment]
thanks for the update. this fixed it.
