### ISSUE TITLE
Launching stash_helper makes my PC nearly freeze (ultra-laggy)

### ISSUE THREAD

**Issue by furopi** [philpw99/Stash_Helper#23]
I kinda get a strange behaviour lately when launching the helper. My PC gets overloaded CPU usage 100%, mouse gets ultra laggy. Any ideas what is causing this?

Thanks, and keep up the good work! We appreciate it! ❤️

Kind regards,
Florian

**Comment by philpw99** [comment]
Sorry, I was too late to come back.. closed

**Comment by furopi** [comment]
Sorry why is it closed? The issue has not been solved yet, as far I can see.... Ty!

**Comment by philpw99** [comment]
Oh, you are still on this issue ? I thought after 4 months of no reply, this issue was becoming stale.
Well, I reopen this issue again.
However, I only have this kind of problem, if I first close the browser then close the helper.
Usually it's a better idea to close the helper first, then the browser will get closed as well.
So can you tell me more about this lagging problem? Like when it will happen, did you see any errors, or did you switch to other browsers...etc.
